/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.usa.vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;


/**
 * 
 * @author ASUS
 */
public class VentanaActualizar extends javax.swing.JFrame {

    public VentanaActualizar() {
                initComponents();
                lblCodigo.setVisible(false);
                txtCodigoActualizado.setVisible(false);
        }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloActualizar = new javax.swing.JLabel();
        lblNombreActualizar = new javax.swing.JLabel();
        lblPrecioActualizar = new javax.swing.JLabel();
        lblInventarioActualizar = new javax.swing.JLabel();
        txtInventarioActualizado = new javax.swing.JTextField();
        txtPrecioActualizado = new javax.swing.JTextField();
        txtNombreActualizado = new javax.swing.JTextField();
        btnActualizarProducto = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        txtCodigoActualizado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualizar Producto");
        setName("frameActualizar"); // NOI18N
        setResizable(false);

        lblTituloActualizar.setText("Ingrese los nuevos valores");

        lblNombreActualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNombreActualizar.setText("Nombre");

        lblPrecioActualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPrecioActualizar.setText("Precio");

        lblInventarioActualizar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblInventarioActualizar.setText("Inventario");

        txtInventarioActualizado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtInventarioActualizado.setToolTipText("");

        txtPrecioActualizado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtNombreActualizado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnActualizarProducto.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnActualizarProducto.setText("Actualizar Producto");

        lblCodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCodigo.setText("Codigo");

        txtCodigoActualizado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCodigoActualizado.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCodigo)
                            .addComponent(lblNombreActualizar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigoActualizado)
                            .addComponent(txtNombreActualizado, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecioActualizar)
                            .addComponent(lblInventarioActualizar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtInventarioActualizado, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(txtPrecioActualizado))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblTituloActualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTituloActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigoActualizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreActualizar)
                    .addComponent(txtNombreActualizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioActualizar)
                    .addComponent(txtPrecioActualizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInventarioActualizar)
                    .addComponent(txtInventarioActualizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * 
 * @param args 
 */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarProducto;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblInventarioActualizar;
    private javax.swing.JLabel lblNombreActualizar;
    private javax.swing.JLabel lblPrecioActualizar;
    private javax.swing.JLabel lblTituloActualizar;
    private javax.swing.JTextField txtCodigoActualizado;
    private javax.swing.JTextField txtInventarioActualizado;
    private javax.swing.JTextField txtNombreActualizado;
    private javax.swing.JTextField txtPrecioActualizado;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnActualizarProducto() {
        return btnActualizarProducto;
    }

    public void setBtnActualizarProducto(JButton btnActualizarProducto) {
        this.btnActualizarProducto = btnActualizarProducto;
    }

    public JLabel getLblInventarioActualizar() {
        return lblInventarioActualizar;
    }

    public void setLblInventarioActualizar(JLabel lblInventarioActualizar) {
        this.lblInventarioActualizar = lblInventarioActualizar;
    }

    public JLabel getLblNombreActualizar() {
        return lblNombreActualizar;
    }

    public void setLblNombreActualizar(JLabel lblNombreActualizar) {
        this.lblNombreActualizar = lblNombreActualizar;
    }

    public JLabel getLblPrecioActualizar() {
        return lblPrecioActualizar;
    }

    public void setLblPrecioActualizar(JLabel lblPrecioActualizar) {
        this.lblPrecioActualizar = lblPrecioActualizar;
    }

    public JLabel getLblTituloActualizar() {
        return lblTituloActualizar;
    }

    public void setLblTituloActualizar(JLabel lblTituloActualizar) {
        this.lblTituloActualizar = lblTituloActualizar;
    }

    public JTextField getTxtInventarioActualizado() {
        return txtInventarioActualizado;
    }

    public void setTxtInventarioActualizado(JTextField txtInventarioActualizado) {
        this.txtInventarioActualizado = txtInventarioActualizado;
    }

    public JTextField getTxtNombreActualizado() {
        return txtNombreActualizado;
    }

    public void setTxtNombreActualizado(JTextField txtNombreActualizado) {
        this.txtNombreActualizado = txtNombreActualizado;
    }

    public JTextField getTxtPrecioActualizado() {
        return txtPrecioActualizado;
    }

    public void setTxtPrecioActualizado(JTextField txtPrecioActualizado) {
        this.txtPrecioActualizado = txtPrecioActualizado;
    }

    public JLabel getLblCodigo() {
        return lblCodigo;
    }

    public void setLblCodigo(JLabel lblCodigo) {
        this.lblCodigo = lblCodigo;
    }

    public JTextField getTxtCodigoActualizado() {
        return txtCodigoActualizado;
    }

    public void setTxtCodigoActualizado(JTextField txtCodigoActualizado) {
        this.txtCodigoActualizado = txtCodigoActualizado;
    }

}
