/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.usa.vista;

import javax.swing.*;
import java.awt.Font;


/**
 * 
 * @author ASUS
 */
public class WindowUpdate extends javax.swing.JFrame {

    public WindowUpdate() {
                initComponents();
                lblCodigo.setVisible(false);
                txtCodigoActualizado.setVisible(false);
        }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Font font = new Font("Tahoma", Font.PLAIN, 12); // NOI18N
        JLabel lblTituloActualizar = new JLabel();
        JLabel lblNombreActualizar = new JLabel();
        JLabel lblPrecioActualizar = new JLabel();
        JLabel lblInventarioActualizar = new JLabel();
        txtInventarioActualizado = new javax.swing.JTextField();
        txtPrecioActualizado = new javax.swing.JTextField();
        txtNombreActualizado = new javax.swing.JTextField();
        btnActualizarProducto = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        txtCodigoActualizado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualizar Producto");
        setName("frameActualizar"); // NOI18N
        setResizable(false);

        lblTituloActualizar.setText("Ingrese los nuevos valores");

        lblNombreActualizar.setFont(font); // NOI18N
        lblNombreActualizar.setText("Nombre");

        lblPrecioActualizar.setFont(font); // NOI18N
        lblPrecioActualizar.setText("Precio");

        lblInventarioActualizar.setFont(font); // NOI18N
        lblInventarioActualizar.setText("Inventario");

        txtInventarioActualizado.setFont(font); // NOI18N
        txtInventarioActualizado.setToolTipText("");

        txtPrecioActualizado.setFont(font); // NOI18N

        txtNombreActualizado.setFont(font); // NOI18N

        btnActualizarProducto.setFont(font); // NOI18N
        btnActualizarProducto.setText("Actualizar Producto");

        lblCodigo.setFont(font); // NOI18N
        lblCodigo.setText("Codigo");

        txtCodigoActualizado.setFont(font); // NOI18N
        txtCodigoActualizado.setHorizontalAlignment(SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCodigo)
                            .addComponent(lblNombreActualizar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigoActualizado)
                            .addComponent(txtNombreActualizado, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecioActualizar)
                            .addComponent(lblInventarioActualizar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtInventarioActualizado, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(txtPrecioActualizado))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblTituloActualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTituloActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigoActualizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreActualizar)
                    .addComponent(txtNombreActualizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioActualizar)
                    .addComponent(txtPrecioActualizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInventarioActualizar)
                    .addComponent(txtInventarioActualizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarProducto;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JTextField txtCodigoActualizado;
    private javax.swing.JTextField txtInventarioActualizado;
    private javax.swing.JTextField txtNombreActualizado;
    private javax.swing.JTextField txtPrecioActualizado;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnActualizarProducto() {
        return btnActualizarProducto;
    }

    public JTextField getTxtInventarioActualizado() {
        return txtInventarioActualizado;
    }

    public JTextField getTxtNombreActualizado() {
        return txtNombreActualizado;
    }


    public JTextField getTxtPrecioActualizado() {
        return txtPrecioActualizado;
    }

    public JTextField getTxtCodigoActualizado() {
        return txtCodigoActualizado;
    }

}
